### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by turner11** [turner11/VQA-MED#12]
- [x] Add model image to GUI [issue](https://github.com/turner11/VQA-MED/issues/26)
- [x] Complete test suite [issue](https://github.com/turner11/VQA-MED/issues/28)
- [ ] Implement Hyperband optimizer [issue](https://github.com/turner11/VQA-MED/issues/29)
- [ ] Optional: test architecture in No-MED data set [issue](https://github.com/turner11/VQA-MED/issues/30)
- [ ] Use multi labels for answers [issue](https://github.com/turner11/VQA-MED/issues/31)
