### ISSUE TITLE
Priorities

### ISSUE THREAD

**Issue by turner11** [turner11/VQA-MED#37]
Split to new issues:

**Version 1**
- [ ] Try adding the category in input (to dense - post merge) - This is only for a general model. [Here is a description](https://github.com/philipperemy/keras-attention-mechanism)
- [x] Try reducing dimension of output (#40 )

**Update**
- [x] Add conv layer where LSTM used to be (#41 )
- [x] Split abnormality into yes-no/VQA questions and have model for each
- [x] Attention layer

Points for paper:
- [ ] Correlation graph between parameters and performance
- [ ] One model to rule them all vs specialists models (#42 )
- [ ] Attention in a general model - merge - adding the category in input (to dense - post merge) - see above
